name: Format code

on:
  pull_request:
    types: [opened, synchronize]
  push:

jobs:
  formatter:
    name: formatter
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22
      - name: Install Dependencies
        run: |
          cd frontend && npm install
          cd ../backend && npm install
      - name: formatting
        run: |
          cd frontend && npx prettier --write src
          cd ../backend && npx prettier --write src
      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Code Formatter
